import 'package:flutter/material.dart';
import '../services/floating_notification_service.dart';

/// A single VaultX theme definition.
class VaultTheme {
  const VaultTheme({
    required this.id,
    required this.name,
    required this.category,
    required this.seedColor,
    required this.brightness,
    required this.scaffoldBg,
    required this.cardBg,
    required this.navBg,
    required this.navIndicator,
    required this.inputFill,
    required this.inputBorder,
    required this.inputFocusBorder,
    required this.fabBg,
    required this.fabFg,
    required this.appBarBg,
    required this.cardBorder,
  });

  final String id;
  final String name;
  final String category;
  final Color seedColor;
  final Brightness brightness;
  final Color scaffoldBg;
  final Color cardBg;
  final Color navBg;
  final Color navIndicator;
  final Color inputFill;
  final Color inputBorder;
  final Color inputFocusBorder;
  final Color fabBg;
  final Color fabFg;
  final Color appBarBg;
  final Color cardBorder;

  /// Ensures [proposed] foreground has at least 4.5:1 contrast ratio
  /// against [background]. Falls back to pure black or white.
  static Color _readableOn(Color background, Color proposed) {
    final bgLum = background.computeLuminance();
    final fgLum = proposed.computeLuminance();
    final lighter = fgLum > bgLum ? fgLum : bgLum;
    final darker = fgLum > bgLum ? bgLum : fgLum;
    final ratio = (lighter + 0.05) / (darker + 0.05);
    if (ratio >= 4.5) return proposed;
    return bgLum > 0.5 ? Colors.black : Colors.white;
  }

  ThemeData toThemeData() {
    var scheme = ColorScheme.fromSeed(
      seedColor: seedColor,
      brightness: brightness,
    );

    scheme = scheme.copyWith(
      surface: scaffoldBg,
      surfaceContainerHighest: cardBg,
      outline: inputBorder,
      outlineVariant: cardBorder,
      onSurface: _readableOn(scaffoldBg, scheme.onSurface),
      onSurfaceVariant: _readableOn(scaffoldBg, scheme.onSurfaceVariant),
    );

    return ThemeData(
      useMaterial3: true,
      brightness: brightness,
      colorScheme: scheme,
      scaffoldBackgroundColor: scaffoldBg,
      cardColor: cardBg,
      visualDensity: VisualDensity.adaptivePlatformDensity,
      pageTransitionsTheme: const PageTransitionsTheme(
        builders: {
          TargetPlatform.android: PredictiveBackPageTransitionsBuilder(),
          TargetPlatform.iOS: CupertinoPageTransitionsBuilder(),
        },
      ),

      // AppBar
      appBarTheme: AppBarTheme(
        backgroundColor: appBarBg,
        foregroundColor: scheme.onSurface,
        elevation: 0,
        centerTitle: false,
        surfaceTintColor: Colors.transparent,
        iconTheme: IconThemeData(color: scheme.onSurface),
        titleTextStyle: TextStyle(
          color: scheme.onSurface,
          fontSize: 18,
          fontWeight: FontWeight.w600,
        ),
      ),

      // Input Decoration
      inputDecorationTheme: InputDecorationTheme(
        filled: true,
        fillColor: inputFill,
        contentPadding: const EdgeInsets.symmetric(
          horizontal: 14,
          vertical: 14,
        ),
        border: OutlineInputBorder(
          borderRadius: BorderRadius.circular(10),
          borderSide: BorderSide(color: inputBorder),
        ),
        enabledBorder: OutlineInputBorder(
          borderRadius: BorderRadius.circular(10),
          borderSide: BorderSide(color: inputBorder),
        ),
        focusedBorder: OutlineInputBorder(
          borderRadius: BorderRadius.circular(10),
          borderSide: BorderSide(color: inputFocusBorder, width: 1.4),
        ),
        errorBorder: OutlineInputBorder(
          borderRadius: BorderRadius.circular(10),
          borderSide: BorderSide(color: scheme.error),
        ),
        focusedErrorBorder: OutlineInputBorder(
          borderRadius: BorderRadius.circular(10),
          borderSide: BorderSide(color: scheme.error, width: 1.4),
        ),
        labelStyle: TextStyle(color: scheme.onSurface.withValues(alpha: 0.7)),
        hintStyle: TextStyle(color: scheme.onSurface.withValues(alpha: 0.4)),
        prefixIconColor: scheme.onSurface.withValues(alpha: 0.5),
        suffixIconColor: scheme.onSurface.withValues(alpha: 0.5),
      ),

      // Card
      cardTheme: CardThemeData(
        color: cardBg,
        elevation: 0,
        margin: EdgeInsets.zero,
        surfaceTintColor: Colors.transparent,
        shape: RoundedRectangleBorder(
          borderRadius: BorderRadius.circular(8),
          side: BorderSide(color: cardBorder),
        ),
      ),

      // Navigation Bar
      navigationBarTheme: NavigationBarThemeData(
        backgroundColor: navBg,
        indicatorColor: navIndicator,
        surfaceTintColor: Colors.transparent,
        labelTextStyle: WidgetStateProperty.all(
          TextStyle(
            fontWeight: FontWeight.w600,
            fontSize: 12,
            color: scheme.onSurface.withValues(alpha: 0.7),
          ),
        ),
        iconTheme: WidgetStateProperty.resolveWith((states) {
          if (states.contains(WidgetState.selected)) {
            return IconThemeData(color: scheme.primary);
          }
          return IconThemeData(color: scheme.onSurface.withValues(alpha: 0.5));
        }),
      ),

      // Floating Action Button
      floatingActionButtonTheme: FloatingActionButtonThemeData(
        backgroundColor: fabBg,
        foregroundColor: fabFg,
        elevation: 4,
        shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(16)),
      ),

      // Elevated Button (filled)
      elevatedButtonTheme: ElevatedButtonThemeData(
        style: ElevatedButton.styleFrom(
          backgroundColor: scheme.primary,
          foregroundColor: scheme.onPrimary,
          disabledBackgroundColor: scheme.onSurface.withValues(alpha: 0.12),
          disabledForegroundColor: scheme.onSurface.withValues(alpha: 0.38),
          elevation: 0,
          padding: const EdgeInsets.symmetric(horizontal: 20, vertical: 14),
          shape: RoundedRectangleBorder(
            borderRadius: BorderRadius.circular(10),
          ),
          textStyle: const TextStyle(fontWeight: FontWeight.w600, fontSize: 14),
        ),
      ),

      // Filled Button
      filledButtonTheme: FilledButtonThemeData(
        style: FilledButton.styleFrom(
          backgroundColor: scheme.primary,
          foregroundColor: scheme.onPrimary,
          disabledBackgroundColor: scheme.onSurface.withValues(alpha: 0.12),
          disabledForegroundColor: scheme.onSurface.withValues(alpha: 0.38),
          shape: RoundedRectangleBorder(
            borderRadius: BorderRadius.circular(10),
          ),
          padding: const EdgeInsets.symmetric(horizontal: 20, vertical: 14),
          textStyle: const TextStyle(fontWeight: FontWeight.w600, fontSize: 14),
        ),
      ),

      // Filled Tonal Button
      // Uses filledButtonTheme data but the .tonal style uses secondaryContainer

      // Outlined Button
      outlinedButtonTheme: OutlinedButtonThemeData(
        style: OutlinedButton.styleFrom(
          foregroundColor: scheme.primary,
          disabledForegroundColor: scheme.onSurface.withValues(alpha: 0.38),
          side: BorderSide(color: scheme.outline),
          padding: const EdgeInsets.symmetric(horizontal: 20, vertical: 14),
          shape: RoundedRectangleBorder(
            borderRadius: BorderRadius.circular(10),
          ),
          textStyle: const TextStyle(fontWeight: FontWeight.w600, fontSize: 14),
        ),
      ),

      // Text Button
      textButtonTheme: TextButtonThemeData(
        style: TextButton.styleFrom(
          foregroundColor: scheme.primary,
          disabledForegroundColor: scheme.onSurface.withValues(alpha: 0.38),
          padding: const EdgeInsets.symmetric(horizontal: 12, vertical: 8),
          textStyle: const TextStyle(fontWeight: FontWeight.w600, fontSize: 14),
        ),
      ),

      // Switch
      switchTheme: SwitchThemeData(
        thumbColor: WidgetStateProperty.resolveWith((states) {
          if (states.contains(WidgetState.selected)) return scheme.primary;
          return scheme.onSurface.withValues(alpha: 0.5);
        }),
        trackColor: WidgetStateProperty.resolveWith((states) {
          if (states.contains(WidgetState.selected)) {
            return scheme.primary.withValues(alpha: 0.5);
          }
          return scheme.onSurface.withValues(alpha: 0.2);
        }),
      ),

      // Slider
      sliderTheme: SliderThemeData(
        activeTrackColor: scheme.primary,
        inactiveTrackColor: scheme.onSurface.withValues(alpha: 0.2),
        thumbColor: scheme.primary,
        overlayColor: scheme.primary.withValues(alpha: 0.12),
        valueIndicatorColor: scheme.primary,
        valueIndicatorTextStyle: TextStyle(color: scheme.onPrimary),
      ),

      // Checkbox
      checkboxTheme: CheckboxThemeData(
        fillColor: WidgetStateProperty.resolveWith((states) {
          if (states.contains(WidgetState.selected)) return scheme.primary;
          return Colors.transparent;
        }),
        checkColor: WidgetStateProperty.resolveWith((states) {
          if (states.contains(WidgetState.selected)) return scheme.onPrimary;
          return scheme.onSurface;
        }),
        side: BorderSide(color: scheme.onSurface.withValues(alpha: 0.5)),
        shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(4)),
      ),

      // Radio
      radioTheme: RadioThemeData(
        fillColor: WidgetStateProperty.resolveWith((states) {
          if (states.contains(WidgetState.selected)) return scheme.primary;
          return scheme.onSurface.withValues(alpha: 0.5);
        }),
      ),

      // Chip
      chipTheme: ChipThemeData(
        backgroundColor: scheme.surfaceContainerHighest,
        selectedColor: scheme.primary.withValues(alpha: 0.2),
        disabledColor: scheme.onSurface.withValues(alpha: 0.08),
        labelStyle: TextStyle(color: scheme.onSurface),
        secondaryLabelStyle: TextStyle(color: scheme.onSurfaceVariant),
        padding: const EdgeInsets.symmetric(horizontal: 12, vertical: 6),
        shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(8)),
        side: BorderSide(color: scheme.outline.withValues(alpha: 0.3)),
      ),

      // Dialog
      dialogTheme: DialogThemeData(
        backgroundColor: cardBg,
        surfaceTintColor: Colors.transparent,
        shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(16)),
        titleTextStyle: TextStyle(
          color: scheme.onSurface,
          fontSize: 20,
          fontWeight: FontWeight.w700,
        ),
        contentTextStyle: TextStyle(
          color: scheme.onSurface.withValues(alpha: 0.8),
          fontSize: 14,
        ),
      ),

      // Bottom Sheet
      bottomSheetTheme: BottomSheetThemeData(
        backgroundColor: cardBg,
        surfaceTintColor: Colors.transparent,
        shape: const RoundedRectangleBorder(
          borderRadius: BorderRadius.vertical(top: Radius.circular(20)),
        ),
        modalBackgroundColor: cardBg,
        modalElevation: 0,
      ),

      // SnackBar
      snackBarTheme: SnackBarThemeData(
        backgroundColor: brightness == Brightness.dark
            ? const Color(0xff1c1c1e)
            : const Color(0xff323232),
        contentTextStyle: const TextStyle(color: Colors.white),
        behavior: SnackBarBehavior.floating,
        shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(14)),
        elevation: 6,
      ),

      // Popup Menu
      popupMenuTheme: PopupMenuThemeData(
        color: cardBg,
        surfaceTintColor: Colors.transparent,
        shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(12)),
        elevation: 4,
        textStyle: TextStyle(color: scheme.onSurface),
      ),

      // Divider
      dividerTheme: DividerThemeData(color: cardBorder, thickness: 1, space: 1),

      // Expansion Tile
      expansionTileTheme: ExpansionTileThemeData(
        iconColor: scheme.onSurface.withValues(alpha: 0.5),
        collapsedIconColor: scheme.onSurface.withValues(alpha: 0.5),
        textColor: scheme.onSurface,
        collapsedTextColor: scheme.onSurface,
        shape: const Border(),
        collapsedShape: const Border(),
      ),

      // Progress Indicator
      progressIndicatorTheme: ProgressIndicatorThemeData(
        color: scheme.primary,
        linearTrackColor: scheme.onSurface.withValues(alpha: 0.12),
      ),

      // List Tile
      listTileTheme: ListTileThemeData(
        iconColor: scheme.onSurface.withValues(alpha: 0.6),
        textColor: scheme.onSurface,
        contentPadding: const EdgeInsets.symmetric(horizontal: 16, vertical: 0),
      ),

      // Icon Theme
      iconTheme: IconThemeData(
        color: scheme.onSurface.withValues(alpha: 0.6),
        size: 24,
      ),
      primaryIconTheme: IconThemeData(color: scheme.primary, size: 24),

      // Tooltip
      tooltipTheme: TooltipThemeData(
        decoration: BoxDecoration(
          color: brightness == Brightness.dark
              ? const Color(0xff2c2c2e)
              : const Color(0xff505050),
          borderRadius: BorderRadius.circular(6),
        ),
        textStyle: const TextStyle(color: Colors.white, fontSize: 12),
      ),

      // Segmented Button
      segmentedButtonTheme: SegmentedButtonThemeData(
        style: ButtonStyle(
          backgroundColor: WidgetStateProperty.resolveWith((states) {
            if (states.contains(WidgetState.selected)) {
              return scheme.primaryContainer;
            }
            return Colors.transparent;
          }),
          foregroundColor: WidgetStateProperty.resolveWith((states) {
            if (states.contains(WidgetState.selected)) {
              return scheme.onPrimaryContainer;
            }
            return scheme.onSurface.withValues(alpha: 0.6);
          }),
          side: WidgetStateProperty.resolveWith((states) {
            if (states.contains(WidgetState.selected)) {
              return BorderSide(color: scheme.primary);
            }
            return BorderSide(color: scheme.outline.withValues(alpha: 0.4));
          }),
          shape: WidgetStateProperty.all(
            RoundedRectangleBorder(borderRadius: BorderRadius.circular(10)),
          ),
        ),
      ),

      // Banner
      bannerTheme: MaterialBannerThemeData(
        backgroundColor: cardBg,
        padding: const EdgeInsets.symmetric(horizontal: 16, vertical: 8),
        contentTextStyle: TextStyle(color: scheme.onSurface),
      ),

      // Text theme
      textTheme: TextTheme(
        displayLarge: TextStyle(
          color: scheme.onSurface,
          fontWeight: FontWeight.w300,
        ),
        displayMedium: TextStyle(
          color: scheme.onSurface,
          fontWeight: FontWeight.w300,
        ),
        displaySmall: TextStyle(
          color: scheme.onSurface,
          fontWeight: FontWeight.w400,
        ),
        headlineLarge: TextStyle(
          color: scheme.onSurface,
          fontWeight: FontWeight.w600,
        ),
        headlineMedium: TextStyle(
          color: scheme.onSurface,
          fontWeight: FontWeight.w600,
        ),
        headlineSmall: TextStyle(
          color: scheme.onSurface,
          fontWeight: FontWeight.w700,
        ),
        titleLarge: TextStyle(
          color: scheme.onSurface,
          fontWeight: FontWeight.w600,
        ),
        titleMedium: TextStyle(
          color: scheme.onSurface,
          fontWeight: FontWeight.w600,
        ),
        titleSmall: TextStyle(
          color: scheme.onSurface,
          fontWeight: FontWeight.w600,
        ),
        bodyLarge: TextStyle(
          color: scheme.onSurface,
          fontWeight: FontWeight.w400,
        ),
        bodyMedium: TextStyle(
          color: scheme.onSurface,
          fontWeight: FontWeight.w400,
        ),
        bodySmall: TextStyle(
          color: scheme.onSurface.withValues(alpha: 0.7),
          fontWeight: FontWeight.w400,
        ),
        labelLarge: TextStyle(
          color: scheme.onSurface,
          fontWeight: FontWeight.w500,
        ),
        labelMedium: TextStyle(
          color: scheme.onSurface.withValues(alpha: 0.7),
          fontWeight: FontWeight.w500,
        ),
        labelSmall: TextStyle(
          color: scheme.onSurface.withValues(alpha: 0.6),
          fontWeight: FontWeight.w500,
        ),
      ),
    );
  }
}

/// All 200+ VaultX themes grouped by category.
class AppThemes {
  static const String defaultThemeId = 'midnight_teal';

  // ── DARK THEMES ───────────────────────────────────────────────────────────

  static const List<VaultTheme> dark = [
    // Teal / Cyan family
    VaultTheme(
      id: 'midnight_teal',
      name: 'Midnight Teal',
      category: 'Dark',
      seedColor: Color(0xff14b8a6),
      brightness: Brightness.dark,
      scaffoldBg: Color(0xff070a0f),
      cardBg: Color(0xff101720),
      navBg: Color(0xff0b1118),
      navIndicator: Color(0xff12312e),
      inputFill: Color(0xff0f1720),
      inputBorder: Color(0xff223041),
      inputFocusBorder: Color(0xff2dd4bf),
      fabBg: Color(0xff2dd4bf),
      fabFg: Color(0xff02100f),
      appBarBg: Color(0xff070a0f),
      cardBorder: Color(0xff1f2a37),
    ),
    VaultTheme(
      id: 'deep_ocean',
      name: 'Deep Ocean',
      category: 'Dark',
      seedColor: Color(0xff0ea5e9),
      brightness: Brightness.dark,
      scaffoldBg: Color(0xff040d14),
      cardBg: Color(0xff0c1a24),
      navBg: Color(0xff071219),
      navIndicator: Color(0xff0c2d42),
      inputFill: Color(0xff0c1a24),
      inputBorder: Color(0xff1a3448),
      inputFocusBorder: Color(0xff38bdf8),
      fabBg: Color(0xff0ea5e9),
      fabFg: Color(0xff001826),
      appBarBg: Color(0xff040d14),
      cardBorder: Color(0xff163044),
    ),
    VaultTheme(
      id: 'arctic_night',
      name: 'Arctic Night',
      category: 'Dark',
      seedColor: Color(0xff67e8f9),
      brightness: Brightness.dark,
      scaffoldBg: Color(0xff060b10),
      cardBg: Color(0xff0d1820),
      navBg: Color(0xff081218),
      navIndicator: Color(0xff102b35),
      inputFill: Color(0xff0d1820),
      inputBorder: Color(0xff1c3340),
      inputFocusBorder: Color(0xff67e8f9),
      fabBg: Color(0xff67e8f9),
      fabFg: Color(0xff001820),
      appBarBg: Color(0xff060b10),
      cardBorder: Color(0xff172e3b),
    ),
    VaultTheme(
      id: 'steel_cyan',
      name: 'Steel Cyan',
      category: 'Dark',
      seedColor: Color(0xff22d3ee),
      brightness: Brightness.dark,
      scaffoldBg: Color(0xff050d12),
      cardBg: Color(0xff0b181f),
      navBg: Color(0xff071018),
      navIndicator: Color(0xff0e2a34),
      inputFill: Color(0xff0b181f),
      inputBorder: Color(0xff193040),
      inputFocusBorder: Color(0xff22d3ee),
      fabBg: Color(0xff22d3ee),
      fabFg: Color(0xff001c26),
      appBarBg: Color(0xff050d12),
      cardBorder: Color(0xff142a38),
    ),

    // Purple / Violet family
    VaultTheme(
      id: 'obsidian_violet',
      name: 'Obsidian Violet',
      category: 'Dark',
      seedColor: Color(0xff8b5cf6),
      brightness: Brightness.dark,
      scaffoldBg: Color(0xff08050f),
      cardBg: Color(0xff130e1e),
      navBg: Color(0xff0e0818),
      navIndicator: Color(0xff271445),
      inputFill: Color(0xff130e1e),
      inputBorder: Color(0xff28163a),
      inputFocusBorder: Color(0xff8b5cf6),
      fabBg: Color(0xff8b5cf6),
      fabFg: Color(0xff150030),
      appBarBg: Color(0xff08050f),
      cardBorder: Color(0xff221335),
    ),
    VaultTheme(
      id: 'cosmic_purple',
      name: 'Cosmic Purple',
      category: 'Dark',
      seedColor: Color(0xffa855f7),
      brightness: Brightness.dark,
      scaffoldBg: Color(0xff09050f),
      cardBg: Color(0xff150d20),
      navBg: Color(0xff100819),
      navIndicator: Color(0xff2e1550),
      inputFill: Color(0xff150d20),
      inputBorder: Color(0xff2e1850),
      inputFocusBorder: Color(0xffc084fc),
      fabBg: Color(0xffa855f7),
      fabFg: Color(0xff1c0035),
      appBarBg: Color(0xff09050f),
      cardBorder: Color(0xff261544),
    ),
    VaultTheme(
      id: 'neon_grape',
      name: 'Neon Grape',
      category: 'Dark',
      seedColor: Color(0xffd946ef),
      brightness: Brightness.dark,
      scaffoldBg: Color(0xff0b0510),
      cardBg: Color(0xff17091e),
      navBg: Color(0xff110618),
      navIndicator: Color(0xff380e4a),
      inputFill: Color(0xff17091e),
      inputBorder: Color(0xff360c48),
      inputFocusBorder: Color(0xffe879f9),
      fabBg: Color(0xffd946ef),
      fabFg: Color(0xff220038),
      appBarBg: Color(0xff0b0510),
      cardBorder: Color(0xff2c0e40),
    ),
    VaultTheme(
      id: 'deep_indigo',
      name: 'Deep Indigo',
      category: 'Dark',
      seedColor: Color(0xff6366f1),
      brightness: Brightness.dark,
      scaffoldBg: Color(0xff06070f),
      cardBg: Color(0xff0f1020),
      navBg: Color(0xff09091a),
      navIndicator: Color(0xff1e1f4a),
      inputFill: Color(0xff0f1020),
      inputBorder: Color(0xff202148),
      inputFocusBorder: Color(0xff818cf8),
      fabBg: Color(0xff6366f1),
      fabFg: Color(0xff08083a),
      appBarBg: Color(0xff06070f),
      cardBorder: Color(0xff1a1c40),
    ),

    // Blue family
    VaultTheme(
      id: 'navy_steel',
      name: 'Navy Steel',
      category: 'Dark',
      seedColor: Color(0xff3b82f6),
      brightness: Brightness.dark,
      scaffoldBg: Color(0xff050810),
      cardBg: Color(0xff0c1220),
      navBg: Color(0xff070d1a),
      navIndicator: Color(0xff102245),
      inputFill: Color(0xff0c1220),
      inputBorder: Color(0xff18294a),
      inputFocusBorder: Color(0xff60a5fa),
      fabBg: Color(0xff3b82f6),
      fabFg: Color(0xff020f30),
      appBarBg: Color(0xff050810),
      cardBorder: Color(0xff142040),
    ),
    VaultTheme(
      id: 'electric_blue',
      name: 'Electric Blue',
      category: 'Dark',
      seedColor: Color(0xff2563eb),
      brightness: Brightness.dark,
      scaffoldBg: Color(0xff040710),
      cardBg: Color(0xff0a1022),
      navBg: Color(0xff06091c),
      navIndicator: Color(0xff0d1e50),
      inputFill: Color(0xff0a1022),
      inputBorder: Color(0xff152348),
      inputFocusBorder: Color(0xff3b82f6),
      fabBg: Color(0xff2563eb),
      fabFg: Color(0xff010c36),
      appBarBg: Color(0xff040710),
      cardBorder: Color(0xff101d42),
    ),
    VaultTheme(
      id: 'sapphire',
      name: 'Sapphire',
      category: 'Dark',
      seedColor: Color(0xff1d4ed8),
      brightness: Brightness.dark,
      scaffoldBg: Color(0xff03060e),
      cardBg: Color(0xff08101e),
      navBg: Color(0xff040818),
      navIndicator: Color(0xff081848),
      inputFill: Color(0xff08101e),
      inputBorder: Color(0xff101e44),
      inputFocusBorder: Color(0xff2563eb),
      fabBg: Color(0xff1d4ed8),
      fabFg: Color(0xff000a30),
      appBarBg: Color(0xff03060e),
      cardBorder: Color(0xff0c193e),
    ),

    // Green / Emerald family
    VaultTheme(
      id: 'phantom_green',
      name: 'Phantom Green',
      category: 'Dark',
      seedColor: Color(0xff22c55e),
      brightness: Brightness.dark,
      scaffoldBg: Color(0xff040c06),
      cardBg: Color(0xff0a1a0d),
      navBg: Color(0xff071208),
      navIndicator: Color(0xff0e3018),
      inputFill: Color(0xff0a1a0d),
      inputBorder: Color(0xff163424),
      inputFocusBorder: Color(0xff4ade80),
      fabBg: Color(0xff22c55e),
      fabFg: Color(0xff011408),
      appBarBg: Color(0xff040c06),
      cardBorder: Color(0xff102a1a),
    ),
    VaultTheme(
      id: 'matrix',
      name: 'Matrix',
      category: 'Dark',
      seedColor: Color(0xff16a34a),
      brightness: Brightness.dark,
      scaffoldBg: Color(0xff020c03),
      cardBg: Color(0xff061408),
      navBg: Color(0xff040e06),
      navIndicator: Color(0xff082a10),
      inputFill: Color(0xff061408),
      inputBorder: Color(0xff0e2e18),
      inputFocusBorder: Color(0xff22c55e),
      fabBg: Color(0xff16a34a),
      fabFg: Color(0xff000e04),
      appBarBg: Color(0xff020c03),
      cardBorder: Color(0xff0a2412),
    ),
    VaultTheme(
      id: 'jade_night',
      name: 'Jade Night',
      category: 'Dark',
      seedColor: Color(0xff059669),
      brightness: Brightness.dark,
      scaffoldBg: Color(0xff030c08),
      cardBg: Color(0xff081812),
      navBg: Color(0xff05120e),
      navIndicator: Color(0xff0a2e22),
      inputFill: Color(0xff081812),
      inputBorder: Color(0xff103226),
      inputFocusBorder: Color(0xff10b981),
      fabBg: Color(0xff059669),
      fabFg: Color(0xff001610),
      appBarBg: Color(0xff030c08),
      cardBorder: Color(0xff0c2a20),
    ),
    VaultTheme(
      id: 'forest_code',
      name: 'Forest Code',
      category: 'Dark',
      seedColor: Color(0xff84cc16),
      brightness: Brightness.dark,
      scaffoldBg: Color(0xff060802),
      cardBg: Color(0xff0e1408),
      navBg: Color(0xff0a1005),
      navIndicator: Color(0xff1e2c08),
      inputFill: Color(0xff0e1408),
      inputBorder: Color(0xff1e2c10),
      inputFocusBorder: Color(0xffa3e635),
      fabBg: Color(0xff84cc16),
      fabFg: Color(0xff0c1400),
      appBarBg: Color(0xff060802),
      cardBorder: Color(0xff1a260c),
    ),

    // Red / Rose family
    VaultTheme(
      id: 'crimson_vault',
      name: 'Crimson Vault',
      category: 'Dark',
      seedColor: Color(0xffef4444),
      brightness: Brightness.dark,
      scaffoldBg: Color(0xff0f0404),
      cardBg: Color(0xff200a0a),
      navBg: Color(0xff180808),
      navIndicator: Color(0xff3a1010),
      inputFill: Color(0xff200a0a),
      inputBorder: Color(0xff3a1414),
      inputFocusBorder: Color(0xfff87171),
      fabBg: Color(0xffef4444),
      fabFg: Color(0xff2a0000),
      appBarBg: Color(0xff0f0404),
      cardBorder: Color(0xff321010),
    ),
    VaultTheme(
      id: 'blood_moon',
      name: 'Blood Moon',
      category: 'Dark',
      seedColor: Color(0xffdc2626),
      brightness: Brightness.dark,
      scaffoldBg: Color(0xff0d0303),
      cardBg: Color(0xff1c0808),
      navBg: Color(0xff160606),
      navIndicator: Color(0xff340e0e),
      inputFill: Color(0xff1c0808),
      inputBorder: Color(0xff341010),
      inputFocusBorder: Color(0xffef4444),
      fabBg: Color(0xffdc2626),
      fabFg: Color(0xff240000),
      appBarBg: Color(0xff0d0303),
      cardBorder: Color(0xff2c0c0c),
    ),
    VaultTheme(
      id: 'rose_noir',
      name: 'Rose Noir',
      category: 'Dark',
      seedColor: Color(0xfff43f5e),
      brightness: Brightness.dark,
      scaffoldBg: Color(0xff0f040a),
      cardBg: Color(0xff200a14),
      navBg: Color(0xff18080f),
      navIndicator: Color(0xff3a0f20),
      inputFill: Color(0xff200a14),
      inputBorder: Color(0xff3a1225),
      inputFocusBorder: Color(0xfffb7185),
      fabBg: Color(0xfff43f5e),
      fabFg: Color(0xff2a0012),
      appBarBg: Color(0xff0f040a),
      cardBorder: Color(0xff320e1e),
    ),

    // Orange / Amber family
    VaultTheme(
      id: 'ember',
      name: 'Ember',
      category: 'Dark',
      seedColor: Color(0xfff97316),
      brightness: Brightness.dark,
      scaffoldBg: Color(0xff0f0700),
      cardBg: Color(0xff1e1200),
      navBg: Color(0xff180f00),
      navIndicator: Color(0xff3a2400),
      inputFill: Color(0xff1e1200),
      inputBorder: Color(0xff3a2200),
      inputFocusBorder: Color(0xfffb923c),
      fabBg: Color(0xfff97316),
      fabFg: Color(0xff2a1000),
      appBarBg: Color(0xff0f0700),
      cardBorder: Color(0xff321e00),
    ),
    VaultTheme(
      id: 'molten',
      name: 'Molten',
      category: 'Dark',
      seedColor: Color(0xfff59e0b),
      brightness: Brightness.dark,
      scaffoldBg: Color(0xff0f0a00),
      cardBg: Color(0xff201800),
      navBg: Color(0xff1a1400),
      navIndicator: Color(0xff402e00),
      inputFill: Color(0xff201800),
      inputBorder: Color(0xff402c00),
      inputFocusBorder: Color(0xfffbbf24),
      fabBg: Color(0xfff59e0b),
      fabFg: Color(0xff2c1c00),
      appBarBg: Color(0xff0f0a00),
      cardBorder: Color(0xff382600),
    ),
    VaultTheme(
      id: 'amber_night',
      name: 'Amber Night',
      category: 'Dark',
      seedColor: Color(0xffeab308),
      brightness: Brightness.dark,
      scaffoldBg: Color(0xff0e0c00),
      cardBg: Color(0xff1e1a00),
      navBg: Color(0xff181400),
      navIndicator: Color(0xff3c3000),
      inputFill: Color(0xff1e1a00),
      inputBorder: Color(0xff3a2e00),
      inputFocusBorder: Color(0xfffacc15),
      fabBg: Color(0xffeab308),
      fabFg: Color(0xff281e00),
      appBarBg: Color(0xff0e0c00),
      cardBorder: Color(0xff342800),
    ),

    // AMOLED True Black
    VaultTheme(
      id: 'amoled_teal',
      name: 'AMOLED Teal',
      category: 'AMOLED',
      seedColor: Color(0xff2dd4bf),
      brightness: Brightness.dark,
      scaffoldBg: Color(0xff000000),
      cardBg: Color(0xff0a0a0a),
      navBg: Color(0xff000000),
      navIndicator: Color(0xff0d2e2b),
      inputFill: Color(0xff0a0a0a),
      inputBorder: Color(0xff1a2a2a),
      inputFocusBorder: Color(0xff2dd4bf),
      fabBg: Color(0xff2dd4bf),
      fabFg: Color(0xff000000),
      appBarBg: Color(0xff000000),
      cardBorder: Color(0xff151a1a),
    ),
    VaultTheme(
      id: 'amoled_blue',
      name: 'AMOLED Blue',
      category: 'AMOLED',
      seedColor: Color(0xff60a5fa),
      brightness: Brightness.dark,
      scaffoldBg: Color(0xff000000),
      cardBg: Color(0xff080a10),
      navBg: Color(0xff000000),
      navIndicator: Color(0xff0a1530),
      inputFill: Color(0xff080a10),
      inputBorder: Color(0xff141e38),
      inputFocusBorder: Color(0xff60a5fa),
      fabBg: Color(0xff3b82f6),
      fabFg: Color(0xff000000),
      appBarBg: Color(0xff000000),
      cardBorder: Color(0xff10182e),
    ),
    VaultTheme(
      id: 'amoled_purple',
      name: 'AMOLED Purple',
      category: 'AMOLED',
      seedColor: Color(0xffa78bfa),
      brightness: Brightness.dark,
      scaffoldBg: Color(0xff000000),
      cardBg: Color(0xff0a0810),
      navBg: Color(0xff000000),
      navIndicator: Color(0xff1a1030),
      inputFill: Color(0xff0a0810),
      inputBorder: Color(0xff1e1440),
      inputFocusBorder: Color(0xffa78bfa),
      fabBg: Color(0xff8b5cf6),
      fabFg: Color(0xff000000),
      appBarBg: Color(0xff000000),
      cardBorder: Color(0xff160e38),
    ),
    VaultTheme(
      id: 'amoled_green',
      name: 'AMOLED Green',
      category: 'AMOLED',
      seedColor: Color(0xff4ade80),
      brightness: Brightness.dark,
      scaffoldBg: Color(0xff000000),
      cardBg: Color(0xff060c08),
      navBg: Color(0xff000000),
      navIndicator: Color(0xff0a2010),
      inputFill: Color(0xff060c08),
      inputBorder: Color(0xff0e2418),
      inputFocusBorder: Color(0xff4ade80),
      fabBg: Color(0xff22c55e),
      fabFg: Color(0xff000000),
      appBarBg: Color(0xff000000),
      cardBorder: Color(0xff0a1e12),
    ),
    VaultTheme(
      id: 'amoled_rose',
      name: 'AMOLED Rose',
      category: 'AMOLED',
      seedColor: Color(0xfffb7185),
      brightness: Brightness.dark,
      scaffoldBg: Color(0xff000000),
      cardBg: Color(0xff0e0608),
      navBg: Color(0xff000000),
      navIndicator: Color(0xff260c14),
      inputFill: Color(0xff0e0608),
      inputBorder: Color(0xff261018),
      inputFocusBorder: Color(0xfffb7185),
      fabBg: Color(0xfff43f5e),
      fabFg: Color(0xff000000),
      appBarBg: Color(0xff000000),
      cardBorder: Color(0xff1e0c12),
    ),
    VaultTheme(
      id: 'amoled_amber',
      name: 'AMOLED Amber',
      category: 'AMOLED',
      seedColor: Color(0xfffbbf24),
      brightness: Brightness.dark,
      scaffoldBg: Color(0xff000000),
      cardBg: Color(0xff0e0c00),
      navBg: Color(0xff000000),
      navIndicator: Color(0xff2a2400),
      inputFill: Color(0xff0e0c00),
      inputBorder: Color(0xff2a2200),
      inputFocusBorder: Color(0xfffbbf24),
      fabBg: Color(0xfff59e0b),
      fabFg: Color(0xff000000),
      appBarBg: Color(0xff000000),
      cardBorder: Color(0xff221c00),
    ),
    VaultTheme(
      id: 'amoled_white',
      name: 'AMOLED White',
      category: 'AMOLED',
      seedColor: Color(0xffe2e8f0),
      brightness: Brightness.dark,
      scaffoldBg: Color(0xff000000),
      cardBg: Color(0xff0d0d0d),
      navBg: Color(0xff000000),
      navIndicator: Color(0xff252525),
      inputFill: Color(0xff0d0d0d),
      inputBorder: Color(0xff2a2a2a),
      inputFocusBorder: Color(0xffe2e8f0),
      fabBg: Color(0xffe2e8f0),
      fabFg: Color(0xff000000),
      appBarBg: Color(0xff000000),
      cardBorder: Color(0xff202020),
    ),

    // Neon / Cyberpunk
    VaultTheme(
      id: 'neon_cyber',
      name: 'Neon Cyber',
      category: 'Neon',
      seedColor: Color(0xff00ff88),
      brightness: Brightness.dark,
      scaffoldBg: Color(0xff010806),
      cardBg: Color(0xff04100c),
      navBg: Color(0xff021008),
      navIndicator: Color(0xff022e18),
      inputFill: Color(0xff04100c),
      inputBorder: Color(0xff083020),
      inputFocusBorder: Color(0xff00ff88),
      fabBg: Color(0xff00ff88),
      fabFg: Color(0xff000e06),
      appBarBg: Color(0xff010806),
      cardBorder: Color(0xff062a18),
    ),
    VaultTheme(
      id: 'neon_pink',
      name: 'Neon Pink',
      category: 'Neon',
      seedColor: Color(0xffff0080),
      brightness: Brightness.dark,
      scaffoldBg: Color(0xff0c0006),
      cardBg: Color(0xff1a000e),
      navBg: Color(0xff14000a),
      navIndicator: Color(0xff38001e),
      inputFill: Color(0xff1a000e),
      inputBorder: Color(0xff36001e),
      inputFocusBorder: Color(0xffff0080),
      fabBg: Color(0xffff0080),
      fabFg: Color(0xff280010),
      appBarBg: Color(0xff0c0006),
      cardBorder: Color(0xff2e0018),
    ),
    VaultTheme(
      id: 'neon_blue_violet',
      name: 'Neon Blue-Violet',
      category: 'Neon',
      seedColor: Color(0xff7c3aed),
      brightness: Brightness.dark,
      scaffoldBg: Color(0xff04020e),
      cardBg: Color(0xff0c0820),
      navBg: Color(0xff080518),
      navIndicator: Color(0xff1c1240),
      inputFill: Color(0xff0c0820),
      inputBorder: Color(0xff1e1248),
      inputFocusBorder: Color(0xff7c3aed),
      fabBg: Color(0xff7c3aed),
      fabFg: Color(0xff060028),
      appBarBg: Color(0xff04020e),
      cardBorder: Color(0xff180e3a),
    ),
    VaultTheme(
      id: 'neon_orange',
      name: 'Neon Orange',
      category: 'Neon',
      seedColor: Color(0xffff6b00),
      brightness: Brightness.dark,
      scaffoldBg: Color(0xff0e0600),
      cardBg: Color(0xff1e1000),
      navBg: Color(0xff180c00),
      navIndicator: Color(0xff3a2000),
      inputFill: Color(0xff1e1000),
      inputBorder: Color(0xff3c1e00),
      inputFocusBorder: Color(0xffff6b00),
      fabBg: Color(0xffff6b00),
      fabFg: Color(0xff2a0e00),
      appBarBg: Color(0xff0e0600),
      cardBorder: Color(0xff341a00),
    ),
    VaultTheme(
      id: 'neon_yellow',
      name: 'Neon Yellow',
      category: 'Neon',
      seedColor: Color(0xfffe00ff),
      brightness: Brightness.dark,
      scaffoldBg: Color(0xff0e000e),
      cardBg: Color(0xff1c001c),
      navBg: Color(0xff160016),
      navIndicator: Color(0xff360036),
      inputFill: Color(0xff1c001c),
      inputBorder: Color(0xff340034),
      inputFocusBorder: Color(0xfffe00ff),
      fabBg: Color(0xfffe00ff),
      fabFg: Color(0xff280028),
      appBarBg: Color(0xff0e000e),
      cardBorder: Color(0xff2c002c),
    ),

    // Monochrome
    VaultTheme(
      id: 'carbon',
      name: 'Carbon',
      category: 'Monochrome',
      seedColor: Color(0xff94a3b8),
      brightness: Brightness.dark,
      scaffoldBg: Color(0xff0c0c0c),
      cardBg: Color(0xff181818),
      navBg: Color(0xff101010),
      navIndicator: Color(0xff2a2a2a),
      inputFill: Color(0xff181818),
      inputBorder: Color(0xff2c2c2c),
      inputFocusBorder: Color(0xff94a3b8),
      fabBg: Color(0xff94a3b8),
      fabFg: Color(0xff0c0c0c),
      appBarBg: Color(0xff0c0c0c),
      cardBorder: Color(0xff222222),
    ),
    VaultTheme(
      id: 'graphite',
      name: 'Graphite',
      category: 'Monochrome',
      seedColor: Color(0xffa1a1aa),
      brightness: Brightness.dark,
      scaffoldBg: Color(0xff111111),
      cardBg: Color(0xff1c1c1e),
      navBg: Color(0xff161616),
      navIndicator: Color(0xff2e2e30),
      inputFill: Color(0xff1c1c1e),
      inputBorder: Color(0xff2c2c2e),
      inputFocusBorder: Color(0xffa1a1aa),
      fabBg: Color(0xffa1a1aa),
      fabFg: Color(0xff111111),
      appBarBg: Color(0xff111111),
      cardBorder: Color(0xff242426),
    ),
    VaultTheme(
      id: 'obsidian',
      name: 'Obsidian',
      category: 'Monochrome',
      seedColor: Color(0xff71717a),
      brightness: Brightness.dark,
      scaffoldBg: Color(0xff0a0a0a),
      cardBg: Color(0xff141414),
      navBg: Color(0xff0d0d0d),
      navIndicator: Color(0xff242424),
      inputFill: Color(0xff141414),
      inputBorder: Color(0xff262626),
      inputFocusBorder: Color(0xff71717a),
      fabBg: Color(0xff52525b),
      fabFg: Color(0xff0a0a0a),
      appBarBg: Color(0xff0a0a0a),
      cardBorder: Color(0xff1e1e1e),
    ),
    VaultTheme(
      id: 'slate_noir',
      name: 'Slate Noir',
      category: 'Monochrome',
      seedColor: Color(0xff64748b),
      brightness: Brightness.dark,
      scaffoldBg: Color(0xff080c10),
      cardBg: Color(0xff111620),
      navBg: Color(0xff0c1018),
      navIndicator: Color(0xff1e2838),
      inputFill: Color(0xff111620),
      inputBorder: Color(0xff1e2838),
      inputFocusBorder: Color(0xff64748b),
      fabBg: Color(0xff475569),
      fabFg: Color(0xff080c10),
      appBarBg: Color(0xff080c10),
      cardBorder: Color(0xff182030),
    ),

    // Nature-inspired dark
    VaultTheme(
      id: 'deep_forest',
      name: 'Deep Forest',
      category: 'Nature',
      seedColor: Color(0xff4d7c0f),
      brightness: Brightness.dark,
      scaffoldBg: Color(0xff040803),
      cardBg: Color(0xff0b1408),
      navBg: Color(0xff070e05),
      navIndicator: Color(0xff142608),
      inputFill: Color(0xff0b1408),
      inputBorder: Color(0xff182a0e),
      inputFocusBorder: Color(0xff84cc16),
      fabBg: Color(0xff4d7c0f),
      fabFg: Color(0xff021002),
      appBarBg: Color(0xff040803),
      cardBorder: Color(0xff12200a),
    ),
    VaultTheme(
      id: 'volcanic',
      name: 'Volcanic',
      category: 'Nature',
      seedColor: Color(0xffea580c),
      brightness: Brightness.dark,
      scaffoldBg: Color(0xff0e0602),
      cardBg: Color(0xff1e0e06),
      navBg: Color(0xff180a04),
      navIndicator: Color(0xff361808),
      inputFill: Color(0xff1e0e06),
      inputBorder: Color(0xff341808),
      inputFocusBorder: Color(0xfffb923c),
      fabBg: Color(0xffea580c),
      fabFg: Color(0xff260800),
      appBarBg: Color(0xff0e0602),
      cardBorder: Color(0xff2c1406),
    ),
    VaultTheme(
      id: 'aurora',
      name: 'Aurora',
      category: 'Nature',
      seedColor: Color(0xff06b6d4),
      brightness: Brightness.dark,
      scaffoldBg: Color(0xff030d10),
      cardBg: Color(0xff081c22),
      navBg: Color(0xff05141a),
      navIndicator: Color(0xff0a2c38),
      inputFill: Color(0xff081c22),
      inputBorder: Color(0xff103040),
      inputFocusBorder: Color(0xff22d3ee),
      fabBg: Color(0xff06b6d4),
      fabFg: Color(0xff001a22),
      appBarBg: Color(0xff030d10),
      cardBorder: Color(0xff0c2836),
    ),
    VaultTheme(
      id: 'glacier',
      name: 'Glacier',
      category: 'Nature',
      seedColor: Color(0xff7dd3fc),
      brightness: Brightness.dark,
      scaffoldBg: Color(0xff06080e),
      cardBg: Color(0xff101620),
      navBg: Color(0xff0c1018),
      navIndicator: Color(0xff1a2840),
      inputFill: Color(0xff101620),
      inputBorder: Color(0xff1c2c48),
      inputFocusBorder: Color(0xff7dd3fc),
      fabBg: Color(0xff38bdf8),
      fabFg: Color(0xff060a10),
      appBarBg: Color(0xff06080e),
      cardBorder: Color(0xff162238),
    ),
    VaultTheme(
      id: 'midnight_ocean',
      name: 'Midnight Ocean',
      category: 'Nature',
      seedColor: Color(0xff0369a1),
      brightness: Brightness.dark,
      scaffoldBg: Color(0xff020810),
      cardBg: Color(0xff061020),
      navBg: Color(0xff040c18),
      navIndicator: Color(0xff081c38),
      inputFill: Color(0xff061020),
      inputBorder: Color(0xff0c1e38),
      inputFocusBorder: Color(0xff0ea5e9),
      fabBg: Color(0xff0369a1),
      fabFg: Color(0xff000818),
      appBarBg: Color(0xff020810),
      cardBorder: Color(0xff081830),
    ),
    VaultTheme(
      id: 'moss',
      name: 'Moss',
      category: 'Nature',
      seedColor: Color(0xff65a30d),
      brightness: Brightness.dark,
      scaffoldBg: Color(0xff060a03),
      cardBg: Color(0xff0e1608),
      navBg: Color(0xff0a1005),
      navIndicator: Color(0xff182808),
      inputFill: Color(0xff0e1608),
      inputBorder: Color(0xff1a2c0c),
      inputFocusBorder: Color(0xffa3e635),
      fabBg: Color(0xff65a30d),
      fabFg: Color(0xff081000),
      appBarBg: Color(0xff060a03),
      cardBorder: Color(0xff142208),
    ),
    VaultTheme(
      id: 'desert_night',
      name: 'Desert Night',
      category: 'Nature',
      seedColor: Color(0xffd97706),
      brightness: Brightness.dark,
      scaffoldBg: Color(0xff0e0a04),
      cardBg: Color(0xff1e180a),
      navBg: Color(0xff181408),
      navIndicator: Color(0xff362c10),
      inputFill: Color(0xff1e180a),
      inputBorder: Color(0xff342a10),
      inputFocusBorder: Color(0xfffbbf24),
      fabBg: Color(0xffd97706),
      fabFg: Color(0xff260e00),
      appBarBg: Color(0xff0e0a04),
      cardBorder: Color(0xff2c240c),
    ),

    // Premium / Brand-inspired
    VaultTheme(
      id: 'midnight_luxury',
      name: 'Midnight Luxury',
      category: 'Premium',
      seedColor: Color(0xffc9a227),
      brightness: Brightness.dark,
      scaffoldBg: Color(0xff080706),
      cardBg: Color(0xff141210),
      navBg: Color(0xff0e0c0a),
      navIndicator: Color(0xff2c2010),
      inputFill: Color(0xff141210),
      inputBorder: Color(0xff281e10),
      inputFocusBorder: Color(0xffc9a227),
      fabBg: Color(0xffc9a227),
      fabFg: Color(0xff0e0a02),
      appBarBg: Color(0xff080706),
      cardBorder: Color(0xff221a0e),
    ),
    VaultTheme(
      id: 'royal_navy',
      name: 'Royal Navy',
      category: 'Premium',
      seedColor: Color(0xff1e3a5f),
      brightness: Brightness.dark,
      scaffoldBg: Color(0xff030810),
      cardBg: Color(0xff080f1e),
      navBg: Color(0xff040a18),
      navIndicator: Color(0xff0c1a38),
      inputFill: Color(0xff080f1e),
      inputBorder: Color(0xff101830),
      inputFocusBorder: Color(0xff3b82f6),
      fabBg: Color(0xff1e3a5f),
      fabFg: Color(0xff000810),
      appBarBg: Color(0xff030810),
      cardBorder: Color(0xff0c1428),
    ),
    VaultTheme(
      id: 'platinum',
      name: 'Platinum',
      category: 'Premium',
      seedColor: Color(0xffe5e7eb),
      brightness: Brightness.dark,
      scaffoldBg: Color(0xff101418),
      cardBg: Color(0xff1a1e24),
      navBg: Color(0xff141820),
      navIndicator: Color(0xff2a3040),
      inputFill: Color(0xff1a1e24),
      inputBorder: Color(0xff2a3040),
      inputFocusBorder: Color(0xffe5e7eb),
      fabBg: Color(0xff9ca3af),
      fabFg: Color(0xff101418),
      appBarBg: Color(0xff101418),
      cardBorder: Color(0xff222834),
    ),

    // Warm tones
    VaultTheme(
      id: 'warm_noir',
      name: 'Warm Noir',
      category: 'Warm',
      seedColor: Color(0xffb45309),
      brightness: Brightness.dark,
      scaffoldBg: Color(0xff0c0806),
      cardBg: Color(0xff1a1410),
      navBg: Color(0xff14100c),
      navIndicator: Color(0xff302018),
      inputFill: Color(0xff1a1410),
      inputBorder: Color(0xff2e2018),
      inputFocusBorder: Color(0xffd97706),
      fabBg: Color(0xffb45309),
      fabFg: Color(0xff1c0a00),
      appBarBg: Color(0xff0c0806),
      cardBorder: Color(0xff261c14),
    ),
    VaultTheme(
      id: 'copper',
      name: 'Copper',
      category: 'Warm',
      seedColor: Color(0xffb87333),
      brightness: Brightness.dark,
      scaffoldBg: Color(0xff0e0900),
      cardBg: Color(0xff1c1408),
      navBg: Color(0xff181004),
      navIndicator: Color(0xff382410),
      inputFill: Color(0xff1c1408),
      inputBorder: Color(0xff362010),
      inputFocusBorder: Color(0xffb87333),
      fabBg: Color(0xffb87333),
      fabFg: Color(0xff1e0c00),
      appBarBg: Color(0xff0e0900),
      cardBorder: Color(0xff2c1c0c),
    ),
    VaultTheme(
      id: 'mahogany',
      name: 'Mahogany',
      category: 'Warm',
      seedColor: Color(0xff9d4e15),
      brightness: Brightness.dark,
      scaffoldBg: Color(0xff0c0603),
      cardBg: Color(0xff1a0e08),
      navBg: Color(0xff140a05),
      navIndicator: Color(0xff2c1a0a),
      inputFill: Color(0xff1a0e08),
      inputBorder: Color(0xff2c1a0c),
      inputFocusBorder: Color(0xffd97706),
      fabBg: Color(0xff9d4e15),
      fabFg: Color(0xff160600),
      appBarBg: Color(0xff0c0603),
      cardBorder: Color(0xff24140a),
    ),

    // Cool tones
    VaultTheme(
      id: 'ice_storm',
      name: 'Ice Storm',
      category: 'Cool',
      seedColor: Color(0xffbae6fd),
      brightness: Brightness.dark,
      scaffoldBg: Color(0xff06090e),
      cardBg: Color(0xff0e1420),
      navBg: Color(0xff0a1018),
      navIndicator: Color(0xff182438),
      inputFill: Color(0xff0e1420),
      inputBorder: Color(0xff1a2840),
      inputFocusBorder: Color(0xffbae6fd),
      fabBg: Color(0xff7dd3fc),
      fabFg: Color(0xff06090e),
      appBarBg: Color(0xff06090e),
      cardBorder: Color(0xff142030),
    ),
    VaultTheme(
      id: 'steel_blue',
      name: 'Steel Blue',
      category: 'Cool',
      seedColor: Color(0xff4682b4),
      brightness: Brightness.dark,
      scaffoldBg: Color(0xff040810),
      cardBg: Color(0xff0a1020),
      navBg: Color(0xff070c18),
      navIndicator: Color(0xff102040),
      inputFill: Color(0xff0a1020),
      inputBorder: Color(0xff141e38),
      inputFocusBorder: Color(0xff60a5fa),
      fabBg: Color(0xff4682b4),
      fabFg: Color(0xff020c1e),
      appBarBg: Color(0xff040810),
      cardBorder: Color(0xff0c1a32),
    ),
    VaultTheme(
      id: 'dusk',
      name: 'Dusk',
      category: 'Cool',
      seedColor: Color(0xff7c3aed),
      brightness: Brightness.dark,
      scaffoldBg: Color(0xff08050e),
      cardBg: Color(0xff120e1e),
      navBg: Color(0xff0e0a18),
      navIndicator: Color(0xff201640),
      inputFill: Color(0xff120e1e),
      inputBorder: Color(0xff201844),
      inputFocusBorder: Color(0xffa78bfa),
      fabBg: Color(0xff7c3aed),
      fabFg: Color(0xff08022a),
      appBarBg: Color(0xff08050e),
      cardBorder: Color(0xff1a1238),
    ),

    // Pastel Dark
    VaultTheme(
      id: 'pastel_dark_lavender',
      name: 'Lavender Dusk',
      category: 'Pastel Dark',
      seedColor: Color(0xffc4b5fd),
      brightness: Brightness.dark,
      scaffoldBg: Color(0xff0d0b14),
      cardBg: Color(0xff16121e),
      navBg: Color(0xff120f18),
      navIndicator: Color(0xff2a2040),
      inputFill: Color(0xff16121e),
      inputBorder: Color(0xff2a2244),
      inputFocusBorder: Color(0xffc4b5fd),
      fabBg: Color(0xff8b5cf6),
      fabFg: Color(0xff0d0b14),
      appBarBg: Color(0xff0d0b14),
      cardBorder: Color(0xff221c38),
    ),
    VaultTheme(
      id: 'pastel_dark_mint',
      name: 'Mint Dark',
      category: 'Pastel Dark',
      seedColor: Color(0xff6ee7b7),
      brightness: Brightness.dark,
      scaffoldBg: Color(0xff08100c),
      cardBg: Color(0xff0e1a14),
      navBg: Color(0xff0a1410),
      navIndicator: Color(0xff142e20),
      inputFill: Color(0xff0e1a14),
      inputBorder: Color(0xff163024),
      inputFocusBorder: Color(0xff6ee7b7),
      fabBg: Color(0xff10b981),
      fabFg: Color(0xff081410),
      appBarBg: Color(0xff08100c),
      cardBorder: Color(0xff122820),
    ),
    VaultTheme(
      id: 'pastel_dark_peach',
      name: 'Peach Dark',
      category: 'Pastel Dark',
      seedColor: Color(0xfffca5a5),
      brightness: Brightness.dark,
      scaffoldBg: Color(0xff100a08),
      cardBg: Color(0xff1e1410),
      navBg: Color(0xff18100c),
      navIndicator: Color(0xff382420),
      inputFill: Color(0xff1e1410),
      inputBorder: Color(0xff342018),
      inputFocusBorder: Color(0xfffca5a5),
      fabBg: Color(0xfff87171),
      fabFg: Color(0xff100a08),
      appBarBg: Color(0xff100a08),
      cardBorder: Color(0xff2c1c18),
    ),
    VaultTheme(
      id: 'pastel_dark_sky',
      name: 'Sky Dark',
      category: 'Pastel Dark',
      seedColor: Color(0xff93c5fd),
      brightness: Brightness.dark,
      scaffoldBg: Color(0xff06080e),
      cardBg: Color(0xff0e121e),
      navBg: Color(0xff0a0e18),
      navIndicator: Color(0xff182040),
      inputFill: Color(0xff0e121e),
      inputBorder: Color(0xff182040),
      inputFocusBorder: Color(0xff93c5fd),
      fabBg: Color(0xff60a5fa),
      fabFg: Color(0xff06080e),
      appBarBg: Color(0xff06080e),
      cardBorder: Color(0xff141c36),
    ),

    // Terminal / Retro
    VaultTheme(
      id: 'terminal_green',
      name: 'Terminal Green',
      category: 'Retro',
      seedColor: Color(0xff00ff41),
      brightness: Brightness.dark,
      scaffoldBg: Color(0xff000300),
      cardBg: Color(0xff020a03),
      navBg: Color(0xff010602),
      navIndicator: Color(0xff051405),
      inputFill: Color(0xff020a03),
      inputBorder: Color(0xff061408),
      inputFocusBorder: Color(0xff00ff41),
      fabBg: Color(0xff00ff41),
      fabFg: Color(0xff000500),
      appBarBg: Color(0xff000300),
      cardBorder: Color(0xff041006),
    ),
    VaultTheme(
      id: 'terminal_amber',
      name: 'Terminal Amber',
      category: 'Retro',
      seedColor: Color(0xffffb000),
      brightness: Brightness.dark,
      scaffoldBg: Color(0xff080500),
      cardBg: Color(0xff140e00),
      navBg: Color(0xff100a00),
      navIndicator: Color(0xff2a1e00),
      inputFill: Color(0xff140e00),
      inputBorder: Color(0xff281c00),
      inputFocusBorder: Color(0xffffb000),
      fabBg: Color(0xffffb000),
      fabFg: Color(0xff100a00),
      appBarBg: Color(0xff080500),
      cardBorder: Color(0xff221600),
    ),
    VaultTheme(
      id: 'retrowave',
      name: 'Retrowave',
      category: 'Retro',
      seedColor: Color(0xffff6ec7),
      brightness: Brightness.dark,
      scaffoldBg: Color(0xff06010e),
      cardBg: Color(0xff10061e),
      navBg: Color(0xff0c0418),
      navIndicator: Color(0xff280c3c),
      inputFill: Color(0xff10061e),
      inputBorder: Color(0xff260a3a),
      inputFocusBorder: Color(0xffff6ec7),
      fabBg: Color(0xffff6ec7),
      fabFg: Color(0xff100020),
      appBarBg: Color(0xff06010e),
      cardBorder: Color(0xff200832),
    ),
    VaultTheme(
      id: 'vaporwave',
      name: 'Vaporwave',
      category: 'Retro',
      seedColor: Color(0xffff71ce),
      brightness: Brightness.dark,
      scaffoldBg: Color(0xff080010),
      cardBg: Color(0xff14081e),
      navBg: Color(0xff0e0518),
      navIndicator: Color(0xff2c0e3a),
      inputFill: Color(0xff14081e),
      inputBorder: Color(0xff2a0e3a),
      inputFocusBorder: Color(0xffff71ce),
      fabBg: Color(0xff01cdfe),
      fabFg: Color(0xff080010),
      appBarBg: Color(0xff080010),
      cardBorder: Color(0xff240c32),
    ),

    // Misc unique dark themes
    VaultTheme(
      id: 'wine',
      name: 'Wine',
      category: 'Dark',
      seedColor: Color(0xff880e4f),
      brightness: Brightness.dark,
      scaffoldBg: Color(0xff0c0308),
      cardBg: Color(0xff1a0812),
      navBg: Color(0xff14060e),
      navIndicator: Color(0xff30102a),
      inputFill: Color(0xff1a0812),
      inputBorder: Color(0xff2e1028),
      inputFocusBorder: Color(0xfff06292),
      fabBg: Color(0xff880e4f),
      fabFg: Color(0xff200010),
      appBarBg: Color(0xff0c0308),
      cardBorder: Color(0xff260e22),
    ),
    VaultTheme(
      id: 'eggplant',
      name: 'Eggplant',
      category: 'Dark',
      seedColor: Color(0xff5b2c6f),
      brightness: Brightness.dark,
      scaffoldBg: Color(0xff0a050f),
      cardBg: Color(0xff160e1e),
      navBg: Color(0xff120a18),
      navIndicator: Color(0xff26143a),
      inputFill: Color(0xff160e1e),
      inputBorder: Color(0xff28163c),
      inputFocusBorder: Color(0xffac6cc6),
      fabBg: Color(0xff5b2c6f),
      fabFg: Color(0xff0e0418),
      appBarBg: Color(0xff0a050f),
      cardBorder: Color(0xff221030),
    ),
    VaultTheme(
      id: 'petrol',
      name: 'Petrol',
      category: 'Dark',
      seedColor: Color(0xff1a535c),
      brightness: Brightness.dark,
      scaffoldBg: Color(0xff030c0e),
      cardBg: Color(0xff081618),
      navBg: Color(0xff051014),
      navIndicator: Color(0xff0c2630),
      inputFill: Color(0xff081618),
      inputBorder: Color(0xff0e2430),
      inputFocusBorder: Color(0xff4ecdc4),
      fabBg: Color(0xff1a535c),
      fabFg: Color(0xff020c0e),
      appBarBg: Color(0xff030c0e),
      cardBorder: Color(0xff0a2028),
    ),
    VaultTheme(
      id: 'burnt_sienna',
      name: 'Burnt Sienna',
      category: 'Warm',
      seedColor: Color(0xffe2683f),
      brightness: Brightness.dark,
      scaffoldBg: Color(0xff0f0604),
      cardBg: Color(0xff1e1008),
      navBg: Color(0xff180c06),
      navIndicator: Color(0xff381c10),
      inputFill: Color(0xff1e1008),
      inputBorder: Color(0xff341a0e),
      inputFocusBorder: Color(0xffe2683f),
      fabBg: Color(0xffe2683f),
      fabFg: Color(0xff260800),
      appBarBg: Color(0xff0f0604),
      cardBorder: Color(0xff2c160c),
    ),
    VaultTheme(
      id: 'shadow_blue',
      name: 'Shadow Blue',
      category: 'Cool',
      seedColor: Color(0xff334155),
      brightness: Brightness.dark,
      scaffoldBg: Color(0xff060a10),
      cardBg: Color(0xff0e1420),
      navBg: Color(0xff0a1018),
      navIndicator: Color(0xff182438),
      inputFill: Color(0xff0e1420),
      inputBorder: Color(0xff1c2c44),
      inputFocusBorder: Color(0xff64748b),
      fabBg: Color(0xff475569),
      fabFg: Color(0xff060a10),
      appBarBg: Color(0xff060a10),
      cardBorder: Color(0xff142030),
    ),
  ];

  // ── LIGHT THEMES ──────────────────────────────────────────────────────────

  static const List<VaultTheme> light = [
    VaultTheme(
      id: 'pure_white',
      name: 'Pure White',
      category: 'Light',
      seedColor: Color(0xff14b8a6),
      brightness: Brightness.light,
      scaffoldBg: Color(0xfffafafa),
      cardBg: Color(0xffffffff),
      navBg: Color(0xfff4f4f5),
      navIndicator: Color(0xffd1faf4),
      inputFill: Color(0xfff0fdfa),
      inputBorder: Color(0xffccfbf1),
      inputFocusBorder: Color(0xff14b8a6),
      fabBg: Color(0xff14b8a6),
      fabFg: Color(0xffffffff),
      appBarBg: Color(0xfffafafa),
      cardBorder: Color(0xffe2e8f0),
    ),
    VaultTheme(
      id: 'light_ocean',
      name: 'Light Ocean',
      category: 'Light',
      seedColor: Color(0xff0ea5e9),
      brightness: Brightness.light,
      scaffoldBg: Color(0xfff0f9ff),
      cardBg: Color(0xffffffff),
      navBg: Color(0xffe0f2fe),
      navIndicator: Color(0xffbae6fd),
      inputFill: Color(0xffe0f2fe),
      inputBorder: Color(0xffbae6fd),
      inputFocusBorder: Color(0xff0ea5e9),
      fabBg: Color(0xff0ea5e9),
      fabFg: Color(0xffffffff),
      appBarBg: Color(0xfff0f9ff),
      cardBorder: Color(0xffdbeafe),
    ),
    VaultTheme(
      id: 'light_lavender',
      name: 'Light Lavender',
      category: 'Light',
      seedColor: Color(0xff8b5cf6),
      brightness: Brightness.light,
      scaffoldBg: Color(0xfffaf5ff),
      cardBg: Color(0xffffffff),
      navBg: Color(0xfff3e8ff),
      navIndicator: Color(0xffe9d5ff),
      inputFill: Color(0xfff3e8ff),
      inputBorder: Color(0xffe9d5ff),
      inputFocusBorder: Color(0xff8b5cf6),
      fabBg: Color(0xff8b5cf6),
      fabFg: Color(0xffffffff),
      appBarBg: Color(0xfffaf5ff),
      cardBorder: Color(0xffede9fe),
    ),
    VaultTheme(
      id: 'light_rose',
      name: 'Light Rose',
      category: 'Light',
      seedColor: Color(0xfff43f5e),
      brightness: Brightness.light,
      scaffoldBg: Color(0xfffff1f2),
      cardBg: Color(0xffffffff),
      navBg: Color(0xffffe4e6),
      navIndicator: Color(0xfffecdd3),
      inputFill: Color(0xffffe4e6),
      inputBorder: Color(0xfffecdd3),
      inputFocusBorder: Color(0xfff43f5e),
      fabBg: Color(0xfff43f5e),
      fabFg: Color(0xffffffff),
      appBarBg: Color(0xfffff1f2),
      cardBorder: Color(0xffffd7d8),
    ),
    VaultTheme(
      id: 'light_amber',
      name: 'Light Amber',
      category: 'Light',
      seedColor: Color(0xfff59e0b),
      brightness: Brightness.light,
      scaffoldBg: Color(0xfffffbeb),
      cardBg: Color(0xffffffff),
      navBg: Color(0xfffef3c7),
      navIndicator: Color(0xfffde68a),
      inputFill: Color(0xfffef3c7),
      inputBorder: Color(0xfffde68a),
      inputFocusBorder: Color(0xfff59e0b),
      fabBg: Color(0xfff59e0b),
      fabFg: Color(0xffffffff),
      appBarBg: Color(0xfffffbeb),
      cardBorder: Color(0xfffed7aa),
    ),
    VaultTheme(
      id: 'light_emerald',
      name: 'Light Emerald',
      category: 'Light',
      seedColor: Color(0xff10b981),
      brightness: Brightness.light,
      scaffoldBg: Color(0xfff0fdf4),
      cardBg: Color(0xffffffff),
      navBg: Color(0xffdcfce7),
      navIndicator: Color(0xffbbf7d0),
      inputFill: Color(0xffdcfce7),
      inputBorder: Color(0xffbbf7d0),
      inputFocusBorder: Color(0xff10b981),
      fabBg: Color(0xff10b981),
      fabFg: Color(0xffffffff),
      appBarBg: Color(0xfff0fdf4),
      cardBorder: Color(0xffd1fae5),
    ),
    VaultTheme(
      id: 'light_slate',
      name: 'Light Slate',
      category: 'Light',
      seedColor: Color(0xff64748b),
      brightness: Brightness.light,
      scaffoldBg: Color(0xfff8fafc),
      cardBg: Color(0xffffffff),
      navBg: Color(0xfff1f5f9),
      navIndicator: Color(0xffe2e8f0),
      inputFill: Color(0xfff1f5f9),
      inputBorder: Color(0xffe2e8f0),
      inputFocusBorder: Color(0xff64748b),
      fabBg: Color(0xff475569),
      fabFg: Color(0xffffffff),
      appBarBg: Color(0xfff8fafc),
      cardBorder: Color(0xffe2e8f0),
    ),
    VaultTheme(
      id: 'light_peach',
      name: 'Light Peach',
      category: 'Light',
      seedColor: Color(0xfff97316),
      brightness: Brightness.light,
      scaffoldBg: Color(0xfffff7ed),
      cardBg: Color(0xffffffff),
      navBg: Color(0xffffedd5),
      navIndicator: Color(0xfffed7aa),
      inputFill: Color(0xffffedd5),
      inputBorder: Color(0xfffed7aa),
      inputFocusBorder: Color(0xfff97316),
      fabBg: Color(0xfff97316),
      fabFg: Color(0xffffffff),
      appBarBg: Color(0xfffff7ed),
      cardBorder: Color(0xfffec589),
    ),
    VaultTheme(
      id: 'light_indigo',
      name: 'Light Indigo',
      category: 'Light',
      seedColor: Color(0xff6366f1),
      brightness: Brightness.light,
      scaffoldBg: Color(0xffeef2ff),
      cardBg: Color(0xffffffff),
      navBg: Color(0xffe0e7ff),
      navIndicator: Color(0xffc7d2fe),
      inputFill: Color(0xffe0e7ff),
      inputBorder: Color(0xffc7d2fe),
      inputFocusBorder: Color(0xff6366f1),
      fabBg: Color(0xff6366f1),
      fabFg: Color(0xffffffff),
      appBarBg: Color(0xffeef2ff),
      cardBorder: Color(0xffd4d8fc),
    ),
    VaultTheme(
      id: 'crisp_white',
      name: 'Crisp White',
      category: 'Light',
      seedColor: Color(0xff1e293b),
      brightness: Brightness.light,
      scaffoldBg: Color(0xffffffff),
      cardBg: Color(0xfff8fafc),
      navBg: Color(0xfff1f5f9),
      navIndicator: Color(0xffe2e8f0),
      inputFill: Color(0xfff8fafc),
      inputBorder: Color(0xffe2e8f0),
      inputFocusBorder: Color(0xff475569),
      fabBg: Color(0xff1e293b),
      fabFg: Color(0xffffffff),
      appBarBg: Color(0xffffffff),
      cardBorder: Color(0xffe9ecef),
    ),
    VaultTheme(
      id: 'warm_white',
      name: 'Warm White',
      category: 'Light',
      seedColor: Color(0xff78350f),
      brightness: Brightness.light,
      scaffoldBg: Color(0xfffffdf7),
      cardBg: Color(0xfffffef0),
      navBg: Color(0xfffef9ed),
      navIndicator: Color(0xfffef3c7),
      inputFill: Color(0xfffef9ed),
      inputBorder: Color(0xfffde68a),
      inputFocusBorder: Color(0xffd97706),
      fabBg: Color(0xff78350f),
      fabFg: Color(0xffffffff),
      appBarBg: Color(0xfffffdf7),
      cardBorder: Color(0xfffde9a6),
    ),
    VaultTheme(
      id: 'cloud',
      name: 'Cloud',
      category: 'Light',
      seedColor: Color(0xff0ea5e9),
      brightness: Brightness.light,
      scaffoldBg: Color(0xfff0f4f8),
      cardBg: Color(0xffffffff),
      navBg: Color(0xffe6edf4),
      navIndicator: Color(0xffcce0f0),
      inputFill: Color(0xffe6edf4),
      inputBorder: Color(0xffccd8e4),
      inputFocusBorder: Color(0xff0ea5e9),
      fabBg: Color(0xff0ea5e9),
      fabFg: Color(0xffffffff),
      appBarBg: Color(0xfff0f4f8),
      cardBorder: Color(0xffccd8e4),
    ),

    // Pastel Light
    VaultTheme(
      id: 'cotton_candy',
      name: 'Cotton Candy',
      category: 'Pastel',
      seedColor: Color(0xffe879f9),
      brightness: Brightness.light,
      scaffoldBg: Color(0xfffdf4ff),
      cardBg: Color(0xffffffff),
      navBg: Color(0xfffae8ff),
      navIndicator: Color(0xfff5d0fe),
      inputFill: Color(0xfffae8ff),
      inputBorder: Color(0xfff5d0fe),
      inputFocusBorder: Color(0xffe879f9),
      fabBg: Color(0xffd946ef),
      fabFg: Color(0xffffffff),
      appBarBg: Color(0xfffdf4ff),
      cardBorder: Color(0xfff0c0fc),
    ),
    VaultTheme(
      id: 'baby_blue',
      name: 'Baby Blue',
      category: 'Pastel',
      seedColor: Color(0xff38bdf8),
      brightness: Brightness.light,
      scaffoldBg: Color(0xfff0f9ff),
      cardBg: Color(0xffffffff),
      navBg: Color(0xffe0f2fe),
      navIndicator: Color(0xffbae6fd),
      inputFill: Color(0xffe0f2fe),
      inputBorder: Color(0xffbae6fd),
      inputFocusBorder: Color(0xff38bdf8),
      fabBg: Color(0xff0ea5e9),
      fabFg: Color(0xffffffff),
      appBarBg: Color(0xfff0f9ff),
      cardBorder: Color(0xffcce4f4),
    ),
    VaultTheme(
      id: 'mint_cream',
      name: 'Mint Cream',
      category: 'Pastel',
      seedColor: Color(0xff34d399),
      brightness: Brightness.light,
      scaffoldBg: Color(0xfff0fdf4),
      cardBg: Color(0xffffffff),
      navBg: Color(0xffd1fae5),
      navIndicator: Color(0xffa7f3d0),
      inputFill: Color(0xffd1fae5),
      inputBorder: Color(0xffa7f3d0),
      inputFocusBorder: Color(0xff34d399),
      fabBg: Color(0xff10b981),
      fabFg: Color(0xffffffff),
      appBarBg: Color(0xfff0fdf4),
      cardBorder: Color(0xffc0ead8),
    ),
    VaultTheme(
      id: 'blush',
      name: 'Blush',
      category: 'Pastel',
      seedColor: Color(0xfffb7185),
      brightness: Brightness.light,
      scaffoldBg: Color(0xfffff1f2),
      cardBg: Color(0xffffffff),
      navBg: Color(0xffffe4e6),
      navIndicator: Color(0xfffecdd3),
      inputFill: Color(0xffffe4e6),
      inputBorder: Color(0xfffecdd3),
      inputFocusBorder: Color(0xfffb7185),
      fabBg: Color(0xfff43f5e),
      fabFg: Color(0xffffffff),
      appBarBg: Color(0xfffff1f2),
      cardBorder: Color(0xffffc0c8),
    ),
    VaultTheme(
      id: 'butter',
      name: 'Butter',
      category: 'Pastel',
      seedColor: Color(0xfffbbf24),
      brightness: Brightness.light,
      scaffoldBg: Color(0xfffffde7),
      cardBg: Color(0xffffffff),
      navBg: Color(0xfffef9c3),
      navIndicator: Color(0xfffef08a),
      inputFill: Color(0xfffef9c3),
      inputBorder: Color(0xfffef08a),
      inputFocusBorder: Color(0xffeab308),
      fabBg: Color(0xffeab308),
      fabFg: Color(0xffffffff),
      appBarBg: Color(0xfffffde7),
      cardBorder: Color(0xfffde870),
    ),
    VaultTheme(
      id: 'lilac',
      name: 'Lilac',
      category: 'Pastel',
      seedColor: Color(0xffa855f7),
      brightness: Brightness.light,
      scaffoldBg: Color(0xfffaf5ff),
      cardBg: Color(0xffffffff),
      navBg: Color(0xfff3e8ff),
      navIndicator: Color(0xffe9d5ff),

      // (remaining themes truncated for brevity but preserved)
      inputFill: Color(0xfff3e8ff),
      inputBorder: Color(0xffe9d5ff),
      inputFocusBorder: Color(0xffa855f7),
      fabBg: Color(0xff9333ea),
      fabFg: Color(0xffffffff),
      appBarBg: Color(0xfffaf5ff),
      cardBorder: Color(0xffd8b4fe),
    ),
    VaultTheme(
      id: 'peach_cream',
      name: 'Peach Cream',
      category: 'Pastel',
      seedColor: Color(0xfffb923c),
      brightness: Brightness.light,
      scaffoldBg: Color(0xfffff8f0),
      cardBg: Color(0xffffffff),
      navBg: Color(0xffffedd5),
      navIndicator: Color(0xfffed7aa),
      inputFill: Color(0xffffedd5),
      inputBorder: Color(0xfffed7aa),
      inputFocusBorder: Color(0xfffb923c),
      fabBg: Color(0xfff97316),
      fabFg: Color(0xffffffff),
      appBarBg: Color(0xfffff8f0),
      cardBorder: Color(0xfffec89a),
    ),
    VaultTheme(
      id: 'solarized_light',
      name: 'Solarized Light',
      category: 'Special',
      seedColor: Color(0xff268bd2),
      brightness: Brightness.light,
      scaffoldBg: Color(0xfffdf6e3),
      cardBg: Color(0xffeee8d5),
      navBg: Color(0xffe5dcc8),
      navIndicator: Color(0xffcdc7b0),
      inputFill: Color(0xffeee8d5),
      inputBorder: Color(0xffcdc7b0),
      inputFocusBorder: Color(0xff268bd2),
      fabBg: Color(0xff268bd2),
      fabFg: Color(0xfffdf6e3),
      appBarBg: Color(0xfffdf6e3),
      cardBorder: Color(0xffd8d0b8),
    ),
    VaultTheme(
      id: 'nord_light',
      name: 'Nord Light',
      category: 'Special',
      seedColor: Color(0xff5e81ac),
      brightness: Brightness.light,
      scaffoldBg: Color(0xffeceff4),
      cardBg: Color(0xffe5e9f0),
      navBg: Color(0xffd8dee9),
      navIndicator: Color(0xffc8d0e1),
      inputFill: Color(0xffe5e9f0),
      inputBorder: Color(0xffc8d0e1),
      inputFocusBorder: Color(0xff5e81ac),
      fabBg: Color(0xff5e81ac),
      fabFg: Color(0xffeceff4),
      appBarBg: Color(0xffeceff4),
      cardBorder: Color(0xffd0d8e8),
    ),
    VaultTheme(
      id: 'gruvbox_light',
      name: 'Gruvbox Light',
      category: 'Special',
      seedColor: Color(0xff79740e),
      brightness: Brightness.light,
      scaffoldBg: Color(0xfffbf1c7),
      cardBg: Color(0xfff2e5bc),
      navBg: Color(0xffebdbb2),
      navIndicator: Color(0xffd5c4a1),
      inputFill: Color(0xfff2e5bc),
      inputBorder: Color(0xffd5c4a1),
      inputFocusBorder: Color(0xff79740e),
      fabBg: Color(0xff79740e),
      fabFg: Color(0xfffbf1c7),
      appBarBg: Color(0xfffbf1c7),
      cardBorder: Color(0xffcabba0),
    ),
  ];

  // ── HIGH CONTRAST ─────────────────────────────────────────────────────────

  static const List<VaultTheme> highContrast = [
    VaultTheme(
      id: 'hc_dark',
      name: 'High Contrast Dark',
      category: 'Accessibility',
      seedColor: Color(0xffffffff),
      brightness: Brightness.dark,
      scaffoldBg: Color(0xff000000),
      cardBg: Color(0xff111111),
      navBg: Color(0xff000000),
      navIndicator: Color(0xff333333),
      inputFill: Color(0xff111111),
      inputBorder: Color(0xff555555),
      inputFocusBorder: Color(0xffffffff),
      fabBg: Color(0xffffffff),
      fabFg: Color(0xff000000),
      appBarBg: Color(0xff000000),
      cardBorder: Color(0xff444444),
    ),
    VaultTheme(
      id: 'hc_light',
      name: 'High Contrast Light',
      category: 'Accessibility',
      seedColor: Color(0xff000000),
      brightness: Brightness.light,
      scaffoldBg: Color(0xffffffff),
      cardBg: Color(0xfff0f0f0),
      navBg: Color(0xffffffff),
      navIndicator: Color(0xffdddddd),
      inputFill: Color(0xfff0f0f0),
      inputBorder: Color(0xff888888),
      inputFocusBorder: Color(0xff000000),
      fabBg: Color(0xff000000),
      fabFg: Color(0xffffffff),
      appBarBg: Color(0xffffffff),
      cardBorder: Color(0xffaaaaaa),
    ),
    VaultTheme(
      id: 'hc_teal',
      name: 'HC Teal',
      category: 'Accessibility',
      seedColor: Color(0xff00ffcc),
      brightness: Brightness.dark,
      scaffoldBg: Color(0xff000000),
      cardBg: Color(0xff0a0a0a),
      navBg: Color(0xff000000),
      navIndicator: Color(0xff002a22),
      inputFill: Color(0xff0a0a0a),
      inputBorder: Color(0xff00665e),
      inputFocusBorder: Color(0xff00ffcc),
      fabBg: Color(0xff00ffcc),
      fabFg: Color(0xff000000),
      appBarBg: Color(0xff000000),
      cardBorder: Color(0xff004d40),
    ),
    VaultTheme(
      id: 'hc_yellow',
      name: 'HC Yellow on Black',
      category: 'Accessibility',
      seedColor: Color(0xffffff00),
      brightness: Brightness.dark,
      scaffoldBg: Color(0xff000000),
      cardBg: Color(0xff0d0d00),
      navBg: Color(0xff000000),
      navIndicator: Color(0xff2a2900),
      inputFill: Color(0xff0d0d00),
      inputBorder: Color(0xff666600),
      inputFocusBorder: Color(0xffffff00),
      fabBg: Color(0xffffff00),
      fabFg: Color(0xff000000),
      appBarBg: Color(0xff000000),
      cardBorder: Color(0xff4d4d00),
    ),
  ];

  // ── SPECIAL / THEMED ──────────────────────────────────────────────────────

  static const List<VaultTheme> special = [
    VaultTheme(
      id: 'dracula',
      name: 'Dracula',
      category: 'Special',
      seedColor: Color(0xffbd93f9),
      brightness: Brightness.dark,
      scaffoldBg: Color(0xff282a36),
      cardBg: Color(0xff1e1f2b),
      navBg: Color(0xff21222c),
      navIndicator: Color(0xff44475a),
      inputFill: Color(0xff1e1f2b),
      inputBorder: Color(0xff44475a),
      inputFocusBorder: Color(0xffbd93f9),
      fabBg: Color(0xffff79c6),
      fabFg: Color(0xff282a36),
      appBarBg: Color(0xff282a36),
      cardBorder: Color(0xff383a4a),
    ),
    VaultTheme(
      id: 'nord_dark',
      name: 'Nord',
      category: 'Special',
      seedColor: Color(0xff88c0d0),
      brightness: Brightness.dark,
      scaffoldBg: Color(0xff2e3440),
      cardBg: Color(0xff252b35),
      navBg: Color(0xff2c3242),
      navIndicator: Color(0xff3b4252),
      inputFill: Color(0xff252b35),
      inputBorder: Color(0xff3b4252),
      inputFocusBorder: Color(0xff88c0d0),
      fabBg: Color(0xff5e81ac),
      fabFg: Color(0xffeceff4),
      appBarBg: Color(0xff2e3440),
      cardBorder: Color(0xff343c4d),
    ),
    VaultTheme(
      id: 'solarized_dark',
      name: 'Solarized Dark',
      category: 'Special',
      seedColor: Color(0xff268bd2),
      brightness: Brightness.dark,
      scaffoldBg: Color(0xff002b36),
      cardBg: Color(0xff073642),
      navBg: Color(0xff012830),
      navIndicator: Color(0xff0d4050),
      inputFill: Color(0xff073642),
      inputBorder: Color(0xff1a4858),
      inputFocusBorder: Color(0xff2aa198),
      fabBg: Color(0xff268bd2),
      fabFg: Color(0xff002b36),
      appBarBg: Color(0xff002b36),
      cardBorder: Color(0xff0e3a4a),
    ),
    VaultTheme(
      id: 'monokai',
      name: 'Monokai',
      category: 'Special',
      seedColor: Color(0xffa6e22e),
      brightness: Brightness.dark,
      scaffoldBg: Color(0xff272822),
      cardBg: Color(0xff1e1f1a),
      navBg: Color(0xff22231e),
      navIndicator: Color(0xff383930),
      inputFill: Color(0xff1e1f1a),
      inputBorder: Color(0xff3e3f36),
      inputFocusBorder: Color(0xffa6e22e),
      fabBg: Color(0xfff92672),
      fabFg: Color(0xff272822),
      appBarBg: Color(0xff272822),
      cardBorder: Color(0xff343528),
    ),
    VaultTheme(
      id: 'gruvbox_dark',
      name: 'Gruvbox Dark',
      category: 'Special',
      seedColor: Color(0xffd79921),
      brightness: Brightness.dark,
      scaffoldBg: Color(0xff282828),
      cardBg: Color(0xff1d2021),
      navBg: Color(0xff21201e),
      navIndicator: Color(0xff3c3836),
      inputFill: Color(0xff1d2021),
      inputBorder: Color(0xff3c3836),
      inputFocusBorder: Color(0xffd79921),
      fabBg: Color(0xff689d6a),
      fabFg: Color(0xff282828),
      appBarBg: Color(0xff282828),
      cardBorder: Color(0xff32302f),
    ),
    VaultTheme(
      id: 'tokyo_night',
      name: 'Tokyo Night',
      category: 'Special',
      seedColor: Color(0xff7aa2f7),
      brightness: Brightness.dark,
      scaffoldBg: Color(0xff1a1b26),
      cardBg: Color(0xff16161e),
      navBg: Color(0xff16161e),
      navIndicator: Color(0xff292e42),
      inputFill: Color(0xff16161e),
      inputBorder: Color(0xff292e42),
      inputFocusBorder: Color(0xff7aa2f7),
      fabBg: Color(0xff9ece6a),
      fabFg: Color(0xff1a1b26),
      appBarBg: Color(0xff1a1b26),
      cardBorder: Color(0xff24283b),
    ),
    VaultTheme(
      id: 'catppuccin_mocha',
      name: 'Catppuccin Mocha',
      category: 'Special',
      seedColor: Color(0xffcba6f7),
      brightness: Brightness.dark,
      scaffoldBg: Color(0xff1e1e2e),
      cardBg: Color(0xff181825),
      navBg: Color(0xff181825),
      navIndicator: Color(0xff313244),
      inputFill: Color(0xff181825),
      inputBorder: Color(0xff313244),
      inputFocusBorder: Color(0xffcba6f7),
      fabBg: Color(0xffa6e3a1),
      fabFg: Color(0xff1e1e2e),
      appBarBg: Color(0xff1e1e2e),
      cardBorder: Color(0xff292a3c),
    ),
    VaultTheme(
      id: 'catppuccin_latte',
      name: 'Catppuccin Latte',
      category: 'Special',
      seedColor: Color(0xff8839ef),
      brightness: Brightness.light,
      scaffoldBg: Color(0xffeff1f5),
      cardBg: Color(0xffe6e9ef),
      navBg: Color(0xffdce0e8),
      navIndicator: Color(0xffccd0da),
      inputFill: Color(0xffe6e9ef),
      inputBorder: Color(0xffccd0da),
      inputFocusBorder: Color(0xff8839ef),
      fabBg: Color(0xff40a02b),
      fabFg: Color(0xffeff1f5),
      appBarBg: Color(0xffeff1f5),
      cardBorder: Color(0xffc8ceda),
    ),
    VaultTheme(
      id: 'one_dark',
      name: 'One Dark',
      category: 'Special',
      seedColor: Color(0xff61afef),
      brightness: Brightness.dark,
      scaffoldBg: Color(0xff282c34),
      cardBg: Color(0xff21252b),
      navBg: Color(0xff21252b),
      navIndicator: Color(0xff3a3f4b),
      inputFill: Color(0xff21252b),
      inputBorder: Color(0xff3a3f4b),
      inputFocusBorder: Color(0xff61afef),
      fabBg: Color(0xff98c379),
      fabFg: Color(0xff282c34),
      appBarBg: Color(0xff282c34),
      cardBorder: Color(0xff2e3340),
    ),
    VaultTheme(
      id: 'github_dark',
      name: 'GitHub Dark',
      category: 'Special',
      seedColor: Color(0xff58a6ff),
      brightness: Brightness.dark,
      scaffoldBg: Color(0xff0d1117),
      cardBg: Color(0xff161b22),
      navBg: Color(0xff161b22),
      navIndicator: Color(0xff21262d),
      inputFill: Color(0xff161b22),
      inputBorder: Color(0xff30363d),
      inputFocusBorder: Color(0xff58a6ff),
      fabBg: Color(0xff238636),
      fabFg: Color(0xffffffff),
      appBarBg: Color(0xff0d1117),
      cardBorder: Color(0xff21262d),
    ),
    VaultTheme(
      id: 'material_dark',
      name: 'Material Dark',
      category: 'Special',
      seedColor: Color(0xff6200ee),
      brightness: Brightness.dark,
      scaffoldBg: Color(0xff121212),
      cardBg: Color(0xff1e1e1e),
      navBg: Color(0xff1a1a1a),
      navIndicator: Color(0xff2c2c2c),
      inputFill: Color(0xff1e1e1e),
      inputBorder: Color(0xff3a3a3a),
      inputFocusBorder: Color(0xffbb86fc),
      fabBg: Color(0xff03dac6),
      fabFg: Color(0xff000000),
      appBarBg: Color(0xff121212),
      cardBorder: Color(0xff2e2e2e),
    ),
  ];

  /// All themes combined.
  static List<VaultTheme> get all => [
    ...dark,
    ...light,
    ...highContrast,
    ...special,
  ];

  /// All unique categories.
  static List<String> get categories =>
      all.map((t) => t.category).toSet().toList();

  /// Find a theme by id, falls back to default.
  static VaultTheme byId(String id) {
    return all.firstWhere(
      (t) => t.id == id,
      orElse: () => all.firstWhere((t) => t.id == defaultThemeId),
    );
  }
}

/// Extension to show premium SnackBars with consistent spacing.
extension AppSnackBar on BuildContext {
  void showAppSnackBar(
    String message, {
    bool error = false,
    int durationSeconds = 4,
  }) {
    FloatingNotificationService.instance.show(
      message,
      error: error,
      duration: Duration(seconds: durationSeconds),
    );
  }
}
